apiVersion: v1
data:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fS/TiC8+FR5HntPl,iv:JY0yK3JA2GIfffqvTtygaILN9hZ0w0nnP071k4Fv3xo=,tag:Jl2JA8txkC4FrQo0UcIHyQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:l6Yal+deAQsV6zCiyqbY4Xz0XuMctR/kM8mx5y9FcLrvb4xcGM/YtZ1XWCl/CVzqMfdgX+lII349kJCXAQWzwETJQx2aKVyV96M16OyC94nwpP7MrFuMVg==,iv:EpK9g9mwWLmILzY/2Ri5AO7sePN5WEi/hK9x9VKuq5c=,tag:d7E3MLC8DtRei/rlAorjYQ==,type:str]
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSEFPK3ZJN1gvelRCalVZ
            bWtla3hEVkZBZHNtQjlxWlFGM1RPSmNuK1FrCjBLSTkzUStxS0RwTWhkdW5oYkhi
            QkdOTkNhdE9xd3FJWmQ4VStZRkxySEkKLS0tIGJtQ2xMdGVVSCtyaUZCN0FDTWx1
            UFZ0N1RPTUQzeSs4eUFmekVmR2xsN0UKV0liPpnrEaeTt1257ACF5NzvKGHH0hwO
            nE+tQXtd0RW8Axw9IsNFD2BEjC4JUoX6WIk5jynxAtF+TN14ACISXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:20:52Z"
    mac: ENC[AES256_GCM,data:RCwlKDVeeXSHI4TcupNMctAONzBPCKXitDKTRH6piJsa3YBe8/CCYStIBFZukD13hazqtiKxjulytW7KmCr+4ea98PKwTFpbVfddiNzDpY5RGbwmDI8s84VN/78KyhRxKpZFZkxwwQwdFbKy4zeeI4dvvm/DsY9Kz6qINdC+U8s=,iv:8co2iKzty+DdCdZG2QfM1ye0f97oSaHvUlOLsW0ILO8=,tag:PPr5qGSUA1fFd5cXgVQJPw==,type:str]
    version: 3.13.1
