apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:jxfTJd/+Vvz3Dr4HRwVy0nMeI21b/blzJYPcXzmduI9z+l6sgK5pAh9Q3Fg8dvkgwq8SP1rqhWPw+Vgx,iv:47KPF5fqgKjFkPTyXWWh3IsmFtnsaM4DJ1TDHFWhj5w=,tag:oxBBvIFIIgXfmY1y92FpuQ==,type:str]
    api-secret: ENC[AES256_GCM,data:DXam0CDMqapGU+iWcuqCFUJDkubEmSITgAzPnYIcTdx1ghPWETlK7PgCnlA=,iv:J/sAwAV/F/YrPDDQACnsHn+HyIJ89SHdoNpvjCTjRCY=,tag:nwYmTULe5zzSYSHpjui6iQ==,type:str]
    enc-key-active: ENC[AES256_GCM,data:5v4O0FJusbmGuW4Xpe7M4bsRvY69xaEI,iv:YQrowo7IZeH/TieYvovlUBbJIEgnRKJpa55EsovlPd4=,tag:/HdR2sdunYzo1cI0zw/YKw==,type:str]
    enc-keys: ENC[AES256_GCM,data:UNooPZRZmNpmISfjtMjtx7FNRvoddPtmA5UlZGfD/Mh+jSHNUTCJ6VC3GZI3baWSqR7Ip8zBtKMC3+2bCnCoFQ9lt+ddKhtJy5XLf7UNpzsgg1lk,iv:02AP4opNHUnModIJrh7Tp3VsOdgx4qw+slrp3YjlNKI=,tag:9V8dFeqwnRpoZBPGZX2pHA==,type:str]
    raft-secret: ENC[AES256_GCM,data:x4S20fT82V4ZGIwJvJQq7AEOPWPAvk7ZaCs3Dzfvzxk4K68bJBGDxJ2W2gc=,iv:I9qNwhQxP8020x6OSgcx3Wq8nYyF+E/ot/S5pI3FHAQ=,tag:pNze1CxOJ4Oduup64bzXAw==,type:str]
kind: Secret
metadata:
    name: rauthy-secrets
    namespace: rauthy-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V1NKOVF3bDdyUnd4bkN3
            T1gwTnJvZW1jOHZpblAzMzlQSk1vMDJRa1U0ClRucnRFQndWcStrcDFVdnFrZUF0
            YXQ1d1lDeHAzbXYyRUxwOXZ2MERjbEkKLS0tIDBpMEJLS3Q5eWtGQUkyanFzZnpR
            TUlXQlM0dXBzRnp4YlB1c3Q1SU5PZ0kKOEtk8e0u8n8T/9sUkur34S8hHYAoaYYW
            2m3zwriCNgvVQQoFGGquPSex6f/kMAUC+03ZqjtfqFJjlkm1iFaKwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:20:52Z"
    mac: ENC[AES256_GCM,data:ZrFQkGeAzefg4BsqgKsKhAcsMFf/e097D1H2RX5xVJ3/tocNlcOiKiTW9v5798p/onkV6RAI3Y01R1hqvCoSj77Q8F0luNEIKaZeW5EGpMZipHQ8EUMtpQ6Zh0AdQ6tRtq0u5qbFRq436mOxkTGIxFEt8YQa9tp9BPxpIlPCc+g=,iv:KoSQOJyz9NQdji8qVTiraXy368WqR4IPBY7u7HkbYlc=,tag:zIt9taJt7qMF8UKfG9O07w==,type:str]
    version: 3.13.1
