apiVersion: v1
data:
    from: ENC[AES256_GCM,data:y8m/4Bhi6HDku9W32nlP1LnRCsoe0KsIHPQM/xh5RJQfp14GxFJfxQ==,iv:VTMAT1t+F5fE8D28CyXWQ6G+/DKTHBfy9h9DtWWQjmY=,tag:Ec8VUxju+xdK0saEB8gEJg==,type:str]
    password: ENC[AES256_GCM,data:6Q7SGjHKGiWHwwWF29On2r/Gn+yDPfuL,iv:ir9mm/1cXoiRKzP4wdcwO6t6qC2pffcxGB3YVm5QWjg=,tag:BwpCkye9a/1koBiKF1Uysw==,type:str]
    port: ENC[AES256_GCM,data:KSy7xQ==,iv:wEdUbeHBPIxmSvptu6vnVx8KY4OUVdBUfMRcrZoGoaw=,tag:IAy5COSf7N4OH38YhBhAZA==,type:str]
    starttls_only: ENC[AES256_GCM,data:p7193ddQ+Tk=,iv:5znEsj/K1dg9qmvdkoy9yiQNNjYofNWaaj3ipf4cnbk=,tag:YCtCrv0LvkYMO//7ek5qiQ==,type:str]
    url: ENC[AES256_GCM,data:1AO7lLWl08Sxiz0mxpUGJ+2GQho=,iv:/tGXUSPKFc4sZVsk72cOkrJtPGLPy7NwHozSGVNJjm8=,tag:kK7qce7lil15J9G1cngRqg==,type:str]
    username: ENC[AES256_GCM,data:OX5SqY+5AayBzV/iKoMGO+DYrL6RKAe7,iv:9rdpEJUgqjlCerNYa/QjSjN+9z8sDxeodKuOSvtS8Co=,tag:oWrfWx3+fVQ4VAphX4sHbQ==,type:str]
kind: Secret
metadata:
    name: rauthy-smtp-secret
    namespace: rauthy-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0T1B1aGZMRjBmamVXN0Vw
            V29pWXlMTkg1NmZkcnhpODRqT0JIMFNnblJvCk96N3diQUJvV3BnVm1UYk9ZOTFy
            MFJpZ3lDMW9QRDFlbkNLa2NmaXhxcTQKLS0tIEZNd3JRSlJRdSs4a1Y5MGVoNjBp
            MEpyY2RDdnI5TmRvU21DRmpOL3A5UXcKx/4k9yhkTh3Dk0ZK5JZ9HbSVTlV2gjD7
            F7fkQU5qdydKWK8FPUX/39J0JeN1dxs1k15wJZKOPZn2hfFVhT8tBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvcta0tp0sneq522ktpht0l6ukmhy2avh4p5kf290teadx5afs3q5uumur
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T04:20:52Z"
    mac: ENC[AES256_GCM,data:+/pDwfBdl7TCI4TxvkRog3fR3jbt8jIKW6A62H9hRS1hVfWwSNW0bLs/IImTdYf5dDpqXRG+aA3FeNSkcPDUWa93vRCgjM63gXpkvP9pePDv9oYpnxJQ+4nYdwIqQrMLA6SwvAzygunrJWVWDKwvlhPjHT/nXqxzUtu3gdCL5G4=,iv:xPuCh1riHtQgGkl5MTEFl1HqMki/S9FkMmw3Itw3xxw=,tag:9tYkMtpvH0N7GDeKNKPdBg==,type:str]
    version: 3.13.1
